stage1:
  base_lr: 0.0001 #  00005
  disc_lr: 0.0005 # 0.0001  0.00001 # 5e-4 0.0005
  perceptual_weight: 0.001
  adv_weight: 0.01 
  kl_weight: 0.000001
  params:
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    num_channels: [128, 256]  
    latent_channels: 8 # 4
    num_res_blocks: 2
    attention_levels: [False, False]
    with_encoder_nonlocal_attn: False
    with_decoder_nonlocal_attn: False

discriminator:
  params:
    spatial_dims: 2
    num_channels: 64
    num_layers_d: 3
    in_channels: 1

perceptual_network:
  params:
    spatial_dims: 2
    network_type: "squeeze" #alex