stage1:
  base_lr: 0.00005
  disc_lr: 0.0001
  perceptual_weight: 0.002
  adv_weight: 0.005
  kl_weight: 0.000001
  params:
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    num_channels: [128, 128]
    latent_channels: 15
    num_res_blocks: 2
    norm_num_groups: 32
    attention_levels: [False, False]

discriminator:
  params:
    spatial_dims: 2
    num_channels: 64
    num_layers_d: 3
    in_channels: 1

perceptual_network:
  params:
    spatial_dims: 2
    network_type: "alex"