ldm:
  base_lr: 0.00005
  params:
    spatial_dims: 2
    in_channels: 4
    out_channels: 3
    num_res_blocks: 2
    num_channels: [256, 512, 512, 1024]
    attention_levels: [False, False, True, True]
    num_head_channels: [0, 256, 256, 256]
  scheduler:
    schedule: "linear_beta"
    num_train_timesteps: 1000
    beta_start: 0.0015
    beta_end: 0.0195

#SEM AEKL
# ldm:
#   base_lr: 0.00005
#   params:
#     spatial_dims: 2
#     in_channels: 1
#     out_channels: 1
#     num_res_blocks: 2
#     num_channels: [256, 256]
#     attention_levels: [False, True]
#     num_head_channels: [0, 64]
#   scheduler:
#     schedule: "linear_beta"
#     num_train_timesteps: 1000
#     beta_start: 0.0015
#     beta_end: 0.0195

#SEM AEKL