ldm:
  base_lr: 0.000025
  params:
    spatial_dims: 2
    in_channels: 5 # 4
    out_channels: 4 # 3
    num_res_blocks: 2
    num_channels: [128, 256, 512]
    attention_levels: [False, True, True]
    num_head_channels: [0, 256, 512] 
  scheduler:
    schedule: "linear_beta" # scaled_linear_beta
    num_train_timesteps: 1000
    beta_start: 0.0015 
    beta_end: 0.0205  # 0205
