ldm:
  base_lr: 0.000025
  params:
    spatial_dims: 2
    in_channels: 16
    out_channels: 15
    num_res_blocks: 2
    num_channels: [256, 256]
    attention_levels: [False, True]
    num_head_channels: [0, 64]
  scheduler:
    schedule: "linear_beta"
    num_train_timesteps: 1000
    beta_start: 0.0015
    beta_end: 0.0195